input.onSound(DetectedSound.Loud, function () {
    basic.showIcon(IconNames.Angry)
    music.startMelody(music.builtInMelody(Melodies.Wawawawaa), MelodyOptions.Once)
    basic.pause(1000)
    music.stopAllSounds()
    basic.showIcon(IconNames.Happy)
})
music.setVolume(120)
input.setSoundThreshold(SoundThreshold.Loud, 140)
basic.showIcon(IconNames.Happy)
